### PR TITLE
Clarifying pedagogy

### PR DESCRIPTION
**Pull request by beckynevin**
I've made some pedagogical changes to Citizen_Science_Testing.ipynb. In the process, there are also changes to Citizen_Science_SDK.ipynb and utils.py. Many of the functions have been moved to these two 'utilities'. Also let me know what you think about the grey text, I was trying to get it to contrast with the hyperlinks which are blue and the cell code output (which is black) while still being colorblind friendly.

### CODE REVIEW

**Comment by ericdrosas87** [comment]
Go ahead and merge your SDK notebook changes as-is since I will pretty much be gutting it out with the EPO-8274 branch, and merging your SDK notebook changes here into the new [rubin_citsci_core_pipeline.py](https://github.com/lsst-epo/citizen-science-notebooks/blob/EPO-8274/rubin_citsci_core_pipeline.py) script.

**Comment by ericdrosas87** [comment]
> In this notebook, we include an example of creating a citizen science project on Zooniverse, sending data from RSP to Zooniverse, and retrieving the results of the Zooniverse classification.

I suggest changing the wording here since the notebooks do not actually create the Zooniverse project - that step must be done prior to using the notebooks. We're simply adding a subject set to an existing project.

**Comment by ericdrosas87** [comment]
I've noticed quote a few `<font color='#5A5A5A'>...</font>` tags throughout the Testing notebook. Rather than rely on the `<font>` tag and hardcoding the color code you may find it easier to declare some CSS styling like:

```
.description-text {
    color: #5A5A5A;
}
```

And then you can just use a `<span>` tag with a class like `<span class="description-text">...</span>` rather than the font tag with the hardcoded color code. That way if you ever want to change the tone of the color you only need to do it in one place.

[This StackOverflow Q&A may be helpful in accomplishing this if you choose to implement this change.](https://stackoverflow.com/questions/32156248/how-do-i-set-custom-css-for-my-ipython-ihaskell-jupyter-notebook/33570738#33570738)

**Review by ericdrosas87 — APPROVED** [review]
Otherwise looks good, expect some changes after you merge this once I get my branch merged (which I can make you the reviewer for if you'd like.)

**Comment by beckynevin** [comment]
> 

Question - if I were to go the html cell route, would this still need to be run as a separate cell up top in the notebook? Like, how would it display to the public?

**Comment by beckynevin** [comment]
> > In this notebook, we include an example of creating a citizen science project on Zooniverse, sending data from RSP to Zooniverse, and retrieving the results of the Zooniverse classification.
> 
> I suggest changing the wording here since the notebooks do not actually create the Zooniverse project - that step must be done prior to using the notebooks. We're simply adding a subject set to an existing project.

Great comment, I'm changing to: "In this notebook, we walk the user through an example of how to send data from the RSP to a pre-created Zooniverse project and how to retrieve the results of the Zooniverse classifications."

**Pull request merged**
