### PR TITLE
Removed depr notebooks, pip install citsci package

### PR DESCRIPTION
**Pull request by ericdrosas87**
EPO-8319

### CODE REVIEW

**Comment by ericdrosas87** [comment]
Removed references to deprecated notebooks and added code to install the "backend code" as a PyPI package

**Comment by jsv1206** [comment]
`utils.run_butler_query` is taking much longer time than the version in `main` branch

**Comment by ericdrosas87** [comment]
> `utils.run_butler_query` is taking much longer time than the version in `main` branch

There weren't any changes to the `utils.py` in this PR so the delay is likely unrelated.

**Comment by beckynevin** [comment]
> > `utils.run_butler_query` is taking much longer time than the version in `main` branch
> 
> There weren't any changes to the `utils.py` in this PR so the delay is likely unrelated.

Is this related to Aprajita's comment last week? @ericdrosas87 you seem to have hit the nail on the head with your comment that qserv is to blame.

**Comment by ericdrosas87** [comment]
> Is this related to Aprajita's comment last week? @ericdrosas87 you seem to have hit the nail on the head with your comment that qserv is to blame.

It could be - the last I had heard regarding the QServ outage last week was that an RSP notebook user or users were likely running an unoptimized "naive" query that was eating up all compute resources causing queries to timeout. It sounded like they didn't have a mechanism in place to identify said user(s) or even confirm that this was indeed the case so I think it's still a bit of mystery.

**Comment by ericdrosas87** [comment]
> Is this related to Aprajita's comment last week? @ericdrosas87 you seem to have hit the nail on the head with your comment that qserv is to blame.

Oh but if you are specifically asking if this was a "restart the kernel" kinda fix - also it could be. I'd like to give a more definitive answer, but unfortunately I don't have much insight in the RSP Notebook Aspect world.

**Comment by jsv1206** [comment]
Looks like `rubin_citsci_core_pipeline.py` is missing. 

Should this script be in `citsci_notebook_core_pipeline`? 
There is an import statement in the beginning of the notebook:
`from citsci_notebook_core_pipeline import rubin_citsci_core_pipeline`

Screenshot 2023-08-17 at 10 25 18 AM

**Comment by jsv1206** [comment]
`utils.run_butler_query` now takes ~15 s for 5 images which I think is reasonable?

**Comment by ericdrosas87** [comment]
> `utils.run_butler_query` now takes ~15 s for 5 images which I think is reasonable?

Good to know, nothing from the `utils.py` interacts with the new backend citSci package or EDC so the processing time isn't affected by this change.

**Comment by ericdrosas87** [comment]
> Looks like `rubin_citsci_core_pipeline.py` is missing. I think this needs to be replaced with `cit_sci_pipeline`
> 
> Screenshot 2023-08-17 at 10 25 18 AM

Good catch! I just pushed out an update that explicitly updates the `citsci-notebook-core-pipeline` PyPI package and also swapped out the object name and tested

**Pull request merged**
