### PR TITLE
Verify main citsci notebook meets RTN045 requirements

### PR DESCRIPTION
**Pull request by beckynevin**
Hi all, I'm making this a PR to get some feedback on whether the current notebook meets RTN045 requirements. I did my best to go through and make changes after the accessibility notebook workshop. I'd love to get your 2cents on what we can further improve.

[https://rtn-045.lsst.io/](https://rtn-045.lsst.io/)

### CODE REVIEW

**Review by MelissaGraham — COMMENTED** [review]
I just read through it, did not execute today.

Suggestions (some related to RTN-045 some not):

remove the code cell for style checking

long term, rubin.citsci should be installed in RSP. this is probably already the plan, just add a note saying so.

avoid comments in code cells, to use markdown cells for all comments and narrative, and use the hashtag to comment-out executable (but optional) code

use the imperative voice (instructional; avoid 'you'/'we' statements)

side note, the new image cutout service is available, and a tutorial is nearly ready, which will allow the butler to be avoided. watch https://jira.lsstcorp.org/browse/PREOPS-1150 to get notified of when the tutorial is released.

raw cell should be markdown? "# Trying to figure out..."

S 3.2 Option 2, says "if desirable" but could more guidance be provided to users, example situations why that option would be better, to help users choose between options

**Comment by beckynevin** [comment]
Hi @MelissaGraham , thanks for the comments! So far I've made some changes:

- [ ] Remove the code cell for style check
- [ ] make a note that rubin.citsci will be installed on RSP
- [ ] removing comments from code cells, use # only for commented out code
- [ ] use the imperative voice (remove you/we statements)
- [ ] fixed the strange raw cell
- [ ] removed some repeated text (jupyter error?)
- [ ] S 3.2 Option 2, says "if desirable" but could more guidance be provided to users, example situations why that option would be better, to help users choose between options

**Comment by beckynevin** [comment]
@MelissaGraham , completed my to do list, this is ready for another look-over by you. I offered more guidance in part 3 for manifest file creation. Do you think it's contradictory to say "PIs are welcome to create their own manifest file. This is not the recommended option for PIs new to the citizen science pipeline."

**Comment by beckynevin** [comment]
Also, I think we need a better name for this notebook before we officially merge to main. `Citizen_Science_Testing.ipynb` makes it seem like it's still in development. The name should tell a user what the notebook does (send images to Zooniverse) and the name should also demonstrate the order to run the notebooks in (that this one should be run first). 

What about `01_Introduction_to_Citsci_Pipeline.ipynb`? We could name the variable_stars notebook something like `02_Send_Flipbook_Variable_Stars_Imaging.ipynb`. Thoughts? @MelissaGraham @clareh @ericdrosas87 @bnord

**Comment by MelissaGraham** [comment]
> @MelissaGraham , completed my to do list, this is ready for another look-over by you. I offered more guidance in part 3 for manifest file creation. Do you think it's contradictory to say "PIs are welcome to create their own manifest file. This is not the recommended option for PIs new to the citizen science pipeline."

Yes that sounds reasonable. It's not recommended b/c it's a little harder, yeah?

**Comment by MelissaGraham** [comment]
> Also, I think we need a better name for this notebook before we officially merge to main. `Citizen_Science_Testing.ipynb` makes it seem like it's still in development. The name should tell a user what the notebook does (send images to Zooniverse) and the name should also demonstrate the order to run the notebooks in (that this one should be run first).
> 
> What about `01_Introduction_to_Citsci_Pipeline.ipynb`? We could name the variable_stars notebook something like `02_Send_Flipbook_Variable_Stars_Imaging.ipynb`. Thoughts? @MelissaGraham @clareh @ericdrosas87 @bnord

"01_Introduction_to ...", classic standard, that'll work fine, IMO.

**Pull request merged**
